services:
  - type: web
    name: anagrams-service
    runtime: java
    rootDir: anagrams-service
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar --spring.profiles.active=live
    envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false

  - type: static
    name: anagrams-client
    rootDir: anagrams-client
    buildCommand: npm install && ng build
    staticPublishPath: dist/anagrams-client/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
