spring:
  datasource:
    url: jdbc:h2:mem:WordDB
    driver-class-name: org.h2.Driver
    username: h2
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
mybatis:
  type-aliases-package: bsg.application.anagrams.core
server:
  port: 8080
logging:
  level:
    org.mybatis: DEBUG
