spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anagrams
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

app:
  server-url: "https://anagrams-application.onrender.com/"
  cors:
    allowed-origin-patterns: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS