spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anagrams
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

app:
  cors:
    allowed-origins: "https://anagrams-client.onrender.com"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS